# Generated by Django 4.1.3 on 2022-12-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20221206_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='picture',
            field=models.ImageField(upload_to='rooms/imgs/', verbose_name='Фото'),
        ),
    ]
