# Generated by Django 4.1.3 on 2022-12-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_rooms_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room_image',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(null=True, upload_to='rooms/imgs/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomimage'),
        ),
    ]
