# Generated by Django 3.2.9 on 2022-12-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('post', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
