# Generated by Django 3.2.9 on 2022-12-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Фото профиля'),
        ),
    ]
