# Generated by Django 3.2.9 on 2022-12-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurantmenu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantbook',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='restaurantbook',
            name='last_name',
        ),
        migrations.AddField(
            model_name='restaurantbook',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
