# Generated by Django 3.2.9 on 2022-12-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20221208_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantbook',
            old_name='pesons',
            new_name='persons',
        ),
    ]
