# Generated by Django 4.1.3 on 2022-12-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_pesons_restaurantbook_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
